# Generated by Django 3.0.2 on 2020-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ppic',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
