# Generated by Django 3.0.2 on 2020-05-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_registration_ppic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='sno',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sno',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='sno',
        ),
    ]
