# Generated by Django 3.0.2 on 2020-05-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200524_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='skil',
        ),
    ]
